version: 2.1
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: |
        curl -L -o cirrus https://github.com/cirruslabs/cirrus-cli/releases/latest/download/cirrus-linux-amd64
        sudo mv cirrus /usr/local/bin/cirrus
        sudo chmod +x /usr/local/bin/cirrus
        cd 
        sudo su
        PATH=~/bin:$PATH && curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo 
        chmod a+x ~/bin/repo
        mkdir los
        cd los
        git config --global user.name galang8664
        git config --global user.email ardimasgalang5@gmail.com
        git config --global color.ui false
        repo init --depth=1 --no-repo-verify -u https://github.com/LineageOS/android.git -b lineage-20.0 -g default,-mips,-darwin,-notdefault
        repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8


        

     - run: cirrus run
