version: 2.1
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: |
        curl -L -o cirrus https://github.com/cirruslabs/cirrus-cli/releases/latest/download/cirrus-linux-amd64
        sudo mv cirrus /usr/local/bin/cirrus
        sudo chmod +x /usr/local/bin/cirrus
        PATH=~/bin:$PATH && curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        git config --global user.name galang8664
        git config --global user.email ardimasgalang5@gmail.com
        git config --global color.ui false
        cirrus worker run --token 7st43m2qsm55njdflpbq50m94f8s73kmc27u9p4c5qha9eueqptenjj9uen2s98j7hvou9b1oq9v9dv26pq76863tneh9vg5hosqvb --name lang
     - run: cirrus run